export default function Head() {
  return (
    <>
      <title>Al Fahad</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="https://i0.wp.com/alfahdstore.com/wp-content/uploads/2022/06/cropped-favicon-1.png?fit=32%2C32&ssl=1" />
    </>
  )
}
